spring.application.name=mssc-beer-order-service
spring.profiles.active=localmysql,local-discovery
logging.level.guru=debug
server.port=8081
spring.artemis.user=artemis
spring.artemis.password=simetraehcapa